
all: core-utils-faq.info core-utils-faq.html

core-utils-faq.html: core-utils-faq.texinfo
	makeinfo --html core-utils-faq.texinfo

core-utils-faq.info: core-utils-faq.texinfo
	makeinfo core-utils-faq.texinfo

